trigger:

- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Consider upgrading to a more recent version of Node.js
  displayName: 'Install Node.js'

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'new connection cg'
  displayName: 'Configure BrowserStack'
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'new connection cg'
    browserstackLocal: true


- script: npm install
  displayName: 'Install npm dependencies'

- script: npm install cypress --save-dev
  displayName: 'Install Cypress'

- script: npm install browserstack-cypress-cli
  displayName: 'Install BrowserStack Cypress CLI'

- script: browserstack-cypress run --sync
  displayName: 'Run Cypress tests on BrowserStack'

- task: BrowserStackStopLocal@0