trigger:
  - none

pr:
  - none

parameters:
  - name: Environment
    displayName: Select Environment
    type: string
    default: TEST
    values:
      - TEST
      - QA1

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TEST
    displayName: UI tests on BrowserStack
    condition: eq('${{ parameters.Environment }}', 'TEST')
    jobs:
      - job: EXECUTION1
        timeoutInMinutes: 140
        displayName: EXECUTION
        steps:
          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: |
                npm install -g browserstack-cypress-cli
                npx browserstack-cypress --config-file "browserstack.test.json" run --sync --env grepTags=${env:TAG1}
                exit $LASTEXITCODE
              errorActionPreference: "silentlyContinue"
              warningPreference: "silentlyContinue"
              informationPreference: "silentlyContinue"
              verbosePreference: "silentlyContinue"
              debugPreference: "silentlyContinue"

      - job: EXECUTION2
        dependsOn: EXECUTION1
        condition: succeededOrFailed()
        timeoutInMinutes: 140
        displayName: EXECUTION
        steps:
          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: |
                npm install -g browserstack-cypress-cli
                npx browserstack-cypress --config-file "browserstack.test.json" run --sync --env grepTags=${env:TAG2}
                exit $LASTEXITCODE
              errorActionPreference: "silentlyContinue"
              warningPreference: "silentlyContinue"
              informationPreference: "silentlyContinue"
              verbosePreference: "silentlyContinue"
              debugPreference: "silentlyContinue"