trigger:
  - main

pool:
  name: 'Default' # Use your self-hosted agent pool name

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Upgrade Node.js version if needed
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install npm dependencies'

- script: npm install cypress --save-dev
  displayName: 'Install Cypress'

- script: npm install browserstack-cypress-cli
  displayName: 'Install BrowserStack Cypress CLI'

- script: |
    browserstack-cypress init
    browserstack-cypress run --sync
  displayName: 'Run Cypress tests on BrowserStack Automate'

- script: |
    browserstack-cypress generate-report
  displayName: 'Generate BrowserStack Test Report'
